size_curve_forecasting_task:
  description: >
    Analyze size curve forecasted and percent of each size expected to be sold.
  expected_output: >
    Brief report details about size curve and popular size for different articles.
  agent: size_curve_forecasting_analyst

execute_pipeline_task:
  description: >
    Trigger the execution of the pipeline.
  expected_output: >
    A status report indicating which pipeline was triggered, whether 
    the execution was successful, and the timestamp of execution.
  agent: >
    mlops_expert